### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jrenton** [BenoitZugmeyer/eslint-plugin-html#31] opened 2016-09-22 18:35 UTC
I get this error when trying to run eslint through webpack for `.vue` files.

eslint versions:

```
"eslint": "^3.5.0",
"eslint-config-airbnb-base": "^7.1.0",
"eslint-loader": "^1.5.0",
"eslint-plugin-html": "^1.5.2",
"eslint-plugin-import": "^1.15.0",
```

webpack versions: `"webpack": "^1.12.2",`

`.eslintrc.js` file:

```
module.exports = {
  root: true,
  parserOptions: {
    sourceType: 'module'
  },

  extends: 'airbnb-base',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  rules: {
    'import/no-unresolved': 0,

    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    // allow console.log in dev.
    'no-console': process.env.NODE_ENV === 'production' ? 2 : 0,

    'no-param-reassign': 0,
    'default-case': 0,

    // Sometimes we add propery starting with `_` e.g _type to make
    // sure we dont colide with an existing object property named type.
    'no-underscore-dangle': 0,

    'no-unused-vars': [1, {'vars': 'local', 'args': 'none'}],
  },
}
```

webpack config:

```
module: {
    preLoaders: [
      { test: /\.vue$/, loader: 'eslint', exclude: /node_modules/ }
    ],
},
eslint: {
    failOnWarning: false,
    failOnError: true
},
```

**Comment by BenoitZugmeyer** [comment] 2016-09-24 11:22
Thank you for providing more information on this issue. Closing this issue as it is a duplicate of #28 .

**Closed by BenoitZugmeyer** 2016-09-24 11:22 UTC
